bin/timestamp.log: src/mapconstruction2/Edge.java src/mapconstruction2/Line.java src/mapconstruction2/MapConstruction.java src/mapconstruction2/MapMerging.java src/mapconstruction2/TrackIsolation.java src/mapconstruction2/Vertex.java
	javac -d bin/ src/mapconstruction2/*.java
	touch bin/timestamp.log
